// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ogcprdhsycvasthwchnt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9nY3ByZGhzeWN2YXN0aHdjaG50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwMzM1MDQsImV4cCI6MjA3NDYwOTUwNH0.Ng73tz2XODMFqrJy8pbcYkg_Dgo49vNvkwmeQMx59cw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});